import requests
import hashlib
import time
import os
from playwright.sync_api import sync_playwright
from dotenv import load_dotenv
from datetime import datetime

# Load environment variables
load_dotenv()

# Supabase REST API endpoint i klucz
SUPABASE_URL = os.getenv('SUPABASE_URL')
SUPABASE_API_KEY = os.getenv('SUPABASE_SERVICE_ROLE_KEY')
TABLE = "news"

# Validate required environment variables
if not SUPABASE_URL or not SUPABASE_API_KEY:
    raise ValueError("Missing required environment variables: SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY")

def get_uid(title):
    return hashlib.sha256(title.encode()).hexdigest()

def get_recent_news_from_db():
    """Fetch last 10 news from database to avoid duplicates"""
    url = f"{SUPABASE_URL}/rest/v1/{TABLE}?select=title_raw&order=timestamp.desc&limit=10"
    headers = {
        "apikey": SUPABASE_API_KEY,
        "Authorization": f"Bearer {SUPABASE_API_KEY}"
    }
    try:
        response = requests.get(url, headers=headers)
        if response.status_code == 200:
            return {item['title_raw'] for item in response.json()}
        return set()
    except Exception as e:
        print(f"Error fetching recent news: {e}")
        return set()

def push_to_supabase(news):
    url = f"{SUPABASE_URL}/rest/v1/{TABLE}"
    headers = {
        "apikey": SUPABASE_API_KEY,
        "Authorization": f"Bearer {SUPABASE_API_KEY}",
        "Content-Type": "application/json",
        "Prefer": "resolution=merge-duplicates"
    }
    # Ensure 'title' field exists (required by push_queue trigger)
    # Use title_raw as title if title doesn't exist
    news_data = news.copy()
    if 'title' not in news_data and 'title_raw' in news_data:
        news_data['title'] = news_data['title_raw']
    
    response = requests.post(url, headers=headers, json=news_data)
    print(f"✅ Wysłano: {news_data.get('title_raw', news_data.get('title', 'Unknown'))[:50]}... | Status: {response.status_code}")
    if response.status_code not in [200, 201]:
        print("❌ BŁĄD INSERTU:", response.text)
    return response.status_code in [200, 201]

def extract_news_data(item):
    """Extract all data from a news item"""
    try:
        # Get title
        title_tag = item.query_selector("span.headline-title-nolink")
        if not title_tag:
            return None
        
        title = title_tag.inner_text().strip()
        
        # Get timestamp  
        timestamp_elem = item.query_selector("time, .time, [class*='time']")
        timestamp = timestamp_elem.inner_text().strip() if timestamp_elem else None
        
        # Get tags (country, currency, categories)
        tag_elements = item.query_selector_all("span.tag, .tag, [class*='tag']")
        tags = [tag.inner_text().strip() for tag in tag_elements] if tag_elements else []
        
        # Try to extract country and currency from tags
        country = None
        currency = None
        categories = []
        
        for tag in tags:
            tag_upper = tag.upper()
            # Common currencies
            if tag_upper in ['USD', 'EUR', 'GBP', 'JPY', 'CNY', 'CAD', 'AUD', 'CHF', 'RUB']:
                currency = tag_upper
            # Common countries
            elif tag in ['China', 'US', 'Canada', 'Japan', 'Switzerland', 'Russia', 'Europe']:
                country = tag
            else:
                categories.append(tag)
        
        return {
            "title_raw": title,  # Raw title for AI processing
            "country": country,
            "currency": currency,
            "tags": tags,
            "categories": categories
            # title and ai_explanation will be filled by AI worker
            # timestamp will be auto-generated by DB (DEFAULT NOW())
        }
        
    except Exception as e:
        print(f"Error extracting news data: {e}")
        return None

def find_red_news(page):
    """Find RED (high impact) news from the main news feed"""
    print("\n🔍 SCANNING FOR RED NEWS IN MAIN FEED...")
    
    red_news = []
    
    try:
        # Find all news items in the main feed
        news_items = page.query_selector_all("div.col-xs-12.infinite-item.headline-item")
        print(f"📰 Found {len(news_items)} total news items in feed")
        
        for i, item in enumerate(news_items):
            try:
                # Check if this news item has red styling
                is_red = check_if_red_news(page, item)
                
                if is_red:
                    news_data = extract_news_data(item)
                    if news_data:
                        red_news.append(news_data)
                        print(f"   🔴 RED NEWS: {news_data['title_raw'][:60]}...")
                else:
                    # For debugging - show what we're seeing
                    title_el = item.query_selector("span.headline-title-nolink")
                    if title_el and i < 5:  # Only show first 5 for debugging
                        title = title_el.inner_text().strip()
                        print(f"   ⚪ Regular news: {title[:40]}...")
                        
            except Exception as e:
                print(f"   ❌ Error processing news item {i}: {e}")
        
        return red_news
        
    except Exception as e:
        print(f"❌ Error scanning for red news: {e}")
        return []

def check_if_red_news(page, news_item):
    """Check if a news item is marked as high impact (red) - looks for 'active' class"""
    try:
        # PRIMARY METHOD: Check for "feedWrap active active-critical" pattern
        # From HTML analysis: RED news has "media feedWrap active active-critical"
        feedwrap_element = news_item.query_selector(".media.feedWrap")
        if feedwrap_element:
            feedwrap_classes = feedwrap_element.get_attribute("class") or ""
            if "active-critical" in feedwrap_classes:
                print(f"     🔴 RED NEWS DETECTED: feedWrap classes = '{feedwrap_classes}'")
                return True
            elif "active" in feedwrap_classes and "active-critical" not in feedwrap_classes:
                print(f"     🟡 MEDIUM NEWS: feedWrap classes = '{feedwrap_classes}' (not critical)")
                return False
        
        # BACKUP METHOD: Check main container classes  
        main_classes = news_item.get_attribute("class") or ""
        if "active-critical" in main_classes.lower():
            print(f"     🔴 RED NEWS DETECTED: main classes = '{main_classes}'")
            return True
            
        # BACKUP METHOD 2: Check for red background colors
        bg_color = news_item.evaluate('''(el) => {
            const style = window.getComputedStyle(el);
            return style.backgroundColor;
        }''')
        
        has_red_bg = (
            'red' in bg_color.lower() or
            'rgb(255' in bg_color or
            'rgb(220' in bg_color or
            'rgb(204' in bg_color
        )
        
        if has_red_bg:
            print(f"     🔴 RED NEWS DETECTED: red background = '{bg_color}'")
            return True
            
        return False
        
    except Exception as e:
        print(f"     ❌ Error checking red status: {e}")
        return False

def monitor_news():
    with sync_playwright() as p:
        browser = p.chromium.launch(
            headless=True,  # HEADLESS for VPS (no GUI)
            args=[
                '--no-sandbox',
                '--disable-dev-shm-usage', 
                '--disable-gpu',
                '--disable-extensions',
                '--disable-background-timer-throttling',
                '--disable-renderer-backgrounding',
                '--disable-backgrounding-occluded-windows'
            ]
        )  # Optimized for VPS
        context = browser.new_context(user_agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36")
        page = context.new_page()
        
        print("🌐 Loading Financial Juice...")
        page.goto("https://www.financialjuice.com/home")
        
        try:
            launch_btn = page.query_selector('button:has-text("LAUNCH")')
            if launch_btn:
                print("🚀 Clicking LAUNCH button...")
                launch_btn.click()
                page.wait_for_timeout(2000)
        except Exception as e:
            print(f"⚠️ No LAUNCH button found: {e}")
        
        print("⏳ Waiting for calendar to load...")
        page.wait_for_timeout(3000)  # Wait for dynamic content
        
        # CHECK IF WE GOT REDIRECTED TO LOGIN
        current_url = page.url
        if "accounts.google.com" in current_url or "signin" in current_url.lower() or "login" in current_url.lower():
            print("🚨 REDIRECTED TO LOGIN! Trying to go back to main page...")
            page.goto("https://www.financialjuice.com/home")
            page.wait_for_timeout(3000)
            
            # Try LAUNCH button again
            try:
                launch_btn = page.query_selector('button:has-text("LAUNCH")')
                if launch_btn:
                    print("🚀 Clicking LAUNCH button again...")
                    launch_btn.click()
                    page.wait_for_timeout(2000)
            except Exception as e:
                print(f"⚠️ Error clicking LAUNCH after redirect: {e}")
        
        # HANDLE OVERLAYS MORE CAREFULLY
        print("🛠️ Handling overlays carefully...")
        try:
            # Try to close any modals/signup dialogs first
            try:
                # Close signup modal if present
                signup_modal = page.query_selector('#signup.modal, .modal.fade.in')
                if signup_modal and signup_modal.is_visible():
                    print("   🚫 Closing signup modal...")
                    close_btn = signup_modal.query_selector('button.close, .close, [data-dismiss="modal"]')
                    if close_btn:
                        close_btn.click()
                        page.wait_for_timeout(1000)
            except:
                pass
            
            # Try to click "GO REAL-TIME" with better error handling
            go_realtime_btn = page.query_selector('button:has-text("GO REAL-TIME"), a:has-text("GO REAL-TIME")')
            if go_realtime_btn and go_realtime_btn.is_visible():
                print("   🚀 Clicking GO REAL-TIME button...")
                # Use force click to bypass overlays
                try:
                    go_realtime_btn.click(timeout=5000)
                except:
                    # If normal click fails, try force click using Playwright's text selector
                    try:
                        # Use Playwright's text selector instead of querySelector
                        btn = page.query_selector('button:has-text("GO REAL-TIME"), a:has-text("GO REAL-TIME")')
                        if btn:
                            btn.evaluate('el => el.click()')
                    except:
                        pass
                page.wait_for_timeout(2000)
            else:
                print("   ℹ️ No GO REAL-TIME button found - continuing anyway")
        except Exception as e:
            print(f"   ⚠️ Error handling overlays: {e}")
            print("   ℹ️ Continuing without GO REAL-TIME button...")
        
        # SKIP SCROLLING - FOCUS ON LIVE MONITORING ONLY
        print("🎯 Skipping historical scroll - focusing on LIVE RED NEWS monitoring...")
        print("📡 Ready to detect fresh breaking news as it appears!")
        
        # FINAL COUNT
        final_count = len(page.query_selector_all("div.col-xs-12.infinite-item.headline-item"))
        print(f"📊 FINAL: {final_count} total news items loaded after scrolling")
        
        # Get existing news from database for deduplication
        recent_db_news = get_recent_news_from_db()
        print(f"📋 Found {len(recent_db_news)} recent news in database")
        
        print("\n🔄 Starting LIVE RED NEWS monitoring...")
        print("🎯 Waiting for HIGH IMPACT breaking news with 'active' class...")
        print("📡 Monitoring every 2 seconds, reloading every minute")
        print("🛑 Press Ctrl+C to stop monitoring")
        counter = 0
        
        while True:
            print(f"\n🔍 Scan #{counter + 1} - Looking for RED NEWS...")
            
            # Reload page periodically for fresh data
            if counter % 30 == 0:  # Reload every 30 iterations (every ~1 minute)
                print("🔄 Reloading page for fresh data...")
                page.reload()
                page.wait_for_timeout(3000)
            
            # Find red news in main feed
            red_news_items = find_red_news(page)
            
            if red_news_items:
                print(f"🔴 Found {len(red_news_items)} RED NEWS items!")
                
                # Process each red news item
                for news in red_news_items:
                    # Check if already in database (deduplication by title)
                    if news['title_raw'] not in recent_db_news:
                        print(f"   🆕 NEW RED NEWS: {news['title_raw']}")
                        
                        # Push to database
                        if push_to_supabase(news):
                            recent_db_news.add(news['title_raw'])  # Add to seen set
                            print(f"   ✅ Successfully saved to database")
                        else:
                            print(f"   ❌ Failed to save to database")
                    else:
                        print(f"   🔄 Already exists: {news['title_raw'][:50]}...")
            else:
                print("   📭 No RED NEWS found")
            
            time.sleep(2)  # Check every 2 seconds for faster detection
            counter += 1
            
            # FOR TESTING: Show ALL news to understand structure and find RED ones
            if counter == 1:  # Only on first iteration
                print("\n🔍 DEBUGGING - SCANNING ALL NEWS ITEMS FOR RED ONES:")
                news_items = page.query_selector_all("div.col-xs-12.infinite-item.headline-item")
                print(f"📊 Total news items found after scrolling: {len(news_items)}")
                
                red_found = 0
                # Show MORE news items to see what we have
                for i, item in enumerate(news_items):
                    try:
                        title_el = item.query_selector("span.headline-title-nolink")
                        if title_el:
                            title = title_el.inner_text().strip()
                            
                            # Get comprehensive styling info
                            styling_info = item.evaluate('''(el) => {
                                const style = window.getComputedStyle(el);
                                return {
                                    backgroundColor: style.backgroundColor,
                                    color: style.color,
                                    border: style.border,
                                    borderColor: style.borderColor,
                                    borderLeft: style.borderLeft,
                                    borderRight: style.borderRight,
                                    boxShadow: style.boxShadow
                                };
                            }''')
                            
                            classes = item.get_attribute("class")
                            
                            # Check if this has ACTIVE class (RED NEWS indicator)
                            feedwrap_element = item.query_selector(".media.feedWrap")
                            feedwrap_classes = ""
                            if feedwrap_element:
                                feedwrap_classes = feedwrap_element.get_attribute("class") or ""
                            
                            is_potentially_red = (
                                'active' in feedwrap_classes or
                                'active' in classes.lower() or
                                'red' in str(styling_info).lower() or
                                'rgb(255' in str(styling_info) or
                                'rgb(220' in str(styling_info) or
                                'rgb(204' in str(styling_info)
                            )
                            
                            if is_potentially_red:
                                red_found += 1
                                print(f"\n🔴 POTENTIAL RED NEWS #{red_found}:")
                                print(f"   Title: {title}")
                                print(f"   Classes: {classes}")
                                print(f"   FeedWrap Classes: {feedwrap_classes}")
                                print(f"   Styling: {styling_info}")
                            elif i < 20:  # Show first 20 regular news (not just 10)
                                print(f"\n⚪ Regular News #{i+1}: {title[:60]}...")
                                print(f"     FeedWrap Classes: '{feedwrap_classes}'")
                                
                    except Exception as e:
                        print(f"   ❌ Error processing item {i}: {e}")
                
                print(f"\n📊 SUMMARY: Found {red_found} potentially RED news out of {len(news_items)} total")
                if red_found == 0:
                    print("💤 No active red news currently - monitoring continues...")
                    
                # SHOW LAST 10 NEWS ITEMS (może czerwone są na końcu?)
                print(f"\n🔍 SHOWING LAST 10 NEWS ITEMS:")
                for i in range(max(0, len(news_items) - 10), len(news_items)):
                    try:
                        title_el = news_items[i].query_selector("span.headline-title-nolink")
                        if title_el:
                            title = title_el.inner_text().strip()
                            feedwrap_element = news_items[i].query_selector(".media.feedWrap")
                            feedwrap_classes = ""
                            if feedwrap_element:
                                feedwrap_classes = feedwrap_element.get_attribute("class") or ""
                            print(f"   📰 #{i+1}: {title[:60]}...")
                            print(f"       Classes: '{feedwrap_classes}'")
                    except Exception as e:
                        print(f"   ❌ Error: {e}")
            
            # LIVE MODE - Continue indefinitely until user stops
            # No automatic stop - runs until Ctrl+C
            
        print("\n✅ Monitoring session ended")
        browser.close()

if __name__ == "__main__":
    monitor_news()
